DEVICE_PATH := device/onda/v80se

#For building with minimal manifest
ALLOW_MISSING_DEPENDENCIES := true

#Architecture
TARGET_ARCH := arm64
TARGET_ARCH_VARIANT := armv8-a
TARGET_CPU_ABI := arm64-v8a
TARGET_CPU_VARIANT := generic

TARGET_2ND_ARCH := arm
TARGET_2ND_ARCH_VARIANT := armv7-a-neon
TARGET_2ND_CPU_ABI := armeabi-v7a
TARGET_2ND_CPU_ABI2 := armeabi
TARGET_2ND_CPU_VARIANT := cortex-a15

TARGET_BOARD_SUFFIX := _64
TARGET_USES_64_BIT_BINDER := true

#Kernel
TARGET_IS_64_BIT := true
INSTALLED_KERNEL_TARGET := $(DEVICE_PATH)/prebuilt/kernel
TARGET_PREBUILT_KERNEL := $(DEVICE_PATH)/prebuilt/kernel
TARGET_PREBUILT_RECOVERY_KERNEL := $(DEVICE_PATH)/prebuilt/kernel
BOARD_KERNEL_IMAGE_NAME := kernel
BOARD_KERNEL_CMDLINE :=
BOARD_FLASH_BLOCK_SIZE := 4096
BOARD_KERNEL_BASE := 0x41000000
BOARD_KERNEL_PAGESIZE := 2048
BOARD_MKBOOTIMG_ARGS := --kernel_offset 0x80000

#Bootloader
TARGET_BOOTLOADER_BOARD_NAME := exdroid
TARGET_NO_RECOVERY := false
TARGET_NO_KERNEL := false

#Platform
TARGET_BOARD_PLATFORM := tulip
TARGET_USE_NEON_OPTIMIZATION := true

#Recovery
TARGET_RECOVERY_UI_LIB := librecovery_ui_tulip_chiphd
TARGET_RECOVERY_FSTAB := $(DEVICE_PATH)/recovery/root/etc/recovery.fstab
TARGET_USERIMAGES_USE_EXT4 := true
SW_BOARD_TOUCH_RECOVERY := true

#Renderer
BOARD_EGL_CFG := $(DEVICE_PATH)/egl/egl.cfg
USE_OPENGL_RENDERER := true

#Assert
TARGET_OTA_ASSERT_DEVICE = v80se,v80_se,v80

#TWRP
TW_THEME := landscape_hdpi
TW_HAS_NO_BOOT_PARTITION := true
TW_EXTRA_LANGUAGES := true
TW_SCREEN_BLANK_ON_BOOT := true
TW_INPUT_BLACKLIST := "hbtp_vm"
TW_USE_TOOLBOX := true
